version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - default
  talis_node_dev:
    image: talis/talis-node
    links:
      - redis
    volumes:
      - ".:/var/talis-node"
    command: "/bin/bash"
    environment:
      REDIS_TEST_HOST: "redis"
      REDIS_TEST_PORT: 6379
    networks:
      - default


